name: Jekyll auto-updater
on:
  schedule:
    - cron: '0 9 1 Apr, Oct *'
jobs:
  Bundle update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
      - run: bundle update jekyll
        with:
          ruby-version: "3.3"
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - uses: peter-evans/create-pull-request@v7
        with:
          commit-message: bundle update jekyll
          base: master
          branch: jekyll_update
          delete-branch: true
